version = 0.1
[default.deploy.parameters]
stack_name = "mysql-crud"
resolve_s3 = true
s3_prefix = "mysql-crud"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "DBHost=\"65.2.112.73\" DBUser=\"shahriar\" DBPassword=\"Konok@140116\" DBName=\"crud_db\""
image_repositories = []
confirm_changeset = true
