AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  DBHost:
    Type: String
  DBUser:
    Type: String
  DBPassword:
    Type: String
  DBName:
    Type: String

Globals:
  Function:
    Runtime: python3.12
    Timeout: 10
    MemorySize: 128
    CodeUri: src/functions  # 👈 All functions in one folder
    Environment:
      Variables:
        DB_HOST: !Ref DBHost
        DB_USER: !Ref DBUser
        DB_PASSWORD: !Ref DBPassword
        DB_NAME: !Ref DBName

Resources:
  CreateItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: create_item.lambda_handler  # No folder prefix
      Events:
        ApiCreateItem:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /items
            Method: POST

  ReadItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: read_item.lambda_handler  # No folder prefix
      Events:
        ApiReadItem:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /items/{id}
            Method: GET

  UpdateItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: update_item.lambda_handler  # No folder prefix
      Events:
        ApiUpdateItem:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /items/{id}
            Method: PUT

  DeleteItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: delete_item.lambda_handler  # No folder prefix
      Events:
        ApiDeleteItem:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /items/{id}
            Method: DELETE

  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
